# Date:19/03/2019

In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
car = pd.read_excel("Cars.xlsx")
car.head()

manufacturer model  displ  year  cyl       trans  cty  hwy fl    class
0         audi    a4    1.8  1999    4    auto(l5)   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   16   26  p  compact

In [4]:
len(car)

234

In [6]:
#y = ax + b-------->>>linear equation
#SLR simple linear regression

#i am defining my x and y
x = car[["cty"]]
y = car[["hwy"]]

#crate a blank linear object
lm = LinearRegression()

#fitting the model

model = lm.fit(x,y)

In [10]:
#printing coefficient
print("Coefficient is: ",lm.coef_)

Coefficient is:  [[1.33745561]]


In [9]:
#printing  the value of intercept
print("Intercept is: ",lm.intercept_)

Intercept is:  [0.8920411]


In [13]:
#predict validation

val = pd.DataFrame.from_dict({"cty":[26]})
val

cty
0   26

In [14]:
predict_hwy = model.predict(val)
predict_hwy

array([[35.66588697]])

# -----------------------

In [16]:
#estimate how many would be sold if one day there 50 visitors

In [17]:
drink_data = pd.read_excel("Drinks.xlsx")
drink_data.head()

Day  Number of Visitors  Drinks sold
0     Monday                  32           17
1    Tuesday                  45           20
2  Wednesday                  39           23
3   Thursday                  43            7
4     Friday                  58           24

In [18]:
x = drink_data[["Number of Visitors"]]
y = drink_data[["Drinks sold"]]

In [19]:
lm1 = LinearRegression()
model1 = lm1.fit(x,y)

In [21]:
#printing  the value of intercept
print("Intercept is: ",lm1.intercept_)
#printing coefficient
print("Coefficient is: ",lm1.coef_)

Intercept is:  [-10.19329973]
Coefficient is:  [[0.68129262]]


In [22]:
val1 = pd.DataFrame.from_dict({"Number of Visitors":[50]})
val1

Number of Visitors
0                  50

In [23]:
model1.predict(val1)

array([[23.87133116]])

# -----------------------------------

In [26]:
#step
X = car[["cty"]]
Y = car[["hwy"]]

In [27]:
#step1 split training and test
#strtified samling

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2)

len(X_train),len(X_test),len(Y_train),len(Y_test)

(187, 47, 187, 47)

In [28]:
#create the model

lm2 = LinearRegression()
model2 = lm2.fit(X_train,Y_train)

In [31]:
#predict
Y_test["hwy_pred"] =  model2.predict(X_test)
Y_test.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


hwy   hwy_pred
86    16  18.445436
165   26  29.033036
171   25  26.386136
76    18  17.121986
177   20  22.415786

In [32]:
Y_test["hwy"].mean()

21.574468085106382

In [33]:
Y_test["hwy_pred"].mean()

22.134201246530274

In [34]:
Y_test.corr()

hwy  hwy_pred
hwy       1.000000  0.951986
hwy_pred  0.951986  1.000000

In [37]:
model2.predict(val)

array([[35.65028643]])